### ISSUE TITLE
Need for frequency and power range attributes also with Standard Mode

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#10]
The frequency and power range attributes have not been defined for the standard mode because they are already defined in G.698.2:

https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/pull/4#discussion_r447266914

However, after some discussion with some Q6/15 experts, it seems that G.698.2 does not mandate transceivers to be tunable nor to support tunability for the whole frequency range between the minimum and maximum frequency.

A G.698.2 application code specifies interoperability between two transceivers as long as operating on a central frequency between the minimum and maximum frequency.

A G.698.2 compliant transceiver can support, for a given application code, only one central frequency (within the range specified by G.698.2) or a limited range within the range specified by G.698.2 for that application code.

It is worth noting that operating the transceiver outside of the range specified by G.698.2 for a given application code would not be standard compliant.

Similar considerations apply for the power ranges.

Therefore it seems useful to add also to the standard mode the attributes used to report the frequency and power ranges supported by a given transceiver for a given application code.

**Comment by italobusi** [comment]
At this moment in time, it seems that the `max-total-input-power` would still be not applicable to G.698.2 since G.698.2 is assuming that a receiver can receive only one OTSi.

Further investigation is still on-going to confirm this assumption.

**Comment by italobusi** [comment]
2023-06-13

- [ ] @italobusi @sergiobelotti : to check offline with Q6/15 experts

**Comment by sergiobelotti** [comment]
@all : we succeeded to have feedback from Q6 expert during ITU-T November 2023 meeting in Geneva.
They said that to be compliant to G.698.2 it is not needed the transceivers to support the entire range specified by G.698.2 neither to configure a nominal central frequency. The transceiver need just to support a range (or as extreme case just one frequency) comprised in the entire range specified in G.698.2. 
In the model we need to add also for "standard" mode the attributes related to frequency and power range.
