### ISSUE TITLE
 Transponder typedefs and groupings

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#2]
The intention in this new issue is to encompass together  new and already defined  transponder Yang structures (typedefs, identityrefs, groupings) that can be used by different modules contained in drafts related to transponder.
At minimum these are related drafts:
-draft-ietf-ccamp-dwdm-if-param-yang-03
-draft-ietf-ccamp-optical-impairment-topology-yang-03
-

**Comment by sergiobelotti** [comment]
see: https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/29#issuecomment-610288875

**Comment by italobusi** [comment]
Some initial slides for discussion from me and Gert:

[ot-analysis-01.pptx](https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/files/4558416/ot-analysis-01.pptx)

**Comment by sergiobelotti** [comment]
Uploaded the updated version of the excel file: please review it , feel free to add/modify .  The red text is the new one , after the last meeting.
@haomianzheng : I've tried to reply your comments , column H in blue. 
[transponder-attributes-v2.xlsx](https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/files/4581385/transponder-attributes-v2.xlsx)

**Comment by italobusi** [comment]
Slides updated based on the discussion during the 2020-05-07 call:

[ot-analysis-02.pptx](https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/files/4624948/ot-analysis-02.pptx)

The list of all the possible combinations (including the OTSiG information) is provided within an embedded excel file

**Comment by sergiobelotti** [comment]
see also https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/29#issuecomment-595722529

**Comment by ggrammel** [comment]
added a slide to Italo's for discussion
[ot-analysis-03.pptx](https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/files/4696008/ot-analysis-03.pptx)

**Comment by sergiobelotti** [comment]
The original issue has been already fixed and the new one will be discussed in issue #81
