### ISSUE TITLE
Convention for ITU-T Recommendations

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#26]
I am not sure if there is any convention in YANG modeling to use or not use "." in variable names. For example, in iana-if-type.yang it uses "identity ieee8023adLag" as opposed to "802.3". Maybe just removing ".", to make it like G652, G653.

_Originally posted by @agva123 in https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/pull/25#discussion_r647060343_

- [ ] To be discussed during IETF-111 CCAMP WG presentation

**Comment by italobusi** [comment]
According to https://datatracker.ietf.org/doc/html/rfc8407#section-4.3.1:

>    Identifiers SHOULD follow a consistent naming pattern throughout the
>    module.  Only lowercase letters, numbers, and dashes SHOULD be used
>    in identifier names.  Uppercase characters, the period character, and
>    the underscore character MAY be used if the identifier represents a
>    well-known value that uses these characters.  YANG does not permit
>    any other characters in YANG identifiers.

I think that RFC8407 allows using the . for ITU-T Recommendation numbers since it is a well-know value

**Comment by sergiobelotti** [comment]
April 11 weekly call:
Aihua: I fit is not prohibit the usage of "." , we can use the it also in YANG statements.

**Comment by sergiobelotti** [comment]
the last decision is that "If it is not prohibit the usage of "." , we can use the "." also in YANG statements.
RFC8407 allows using the "." for ITU-T Recommendation numbers since it is a well-know value (see above https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis/issues/26#issuecomment-1503279997)
