### ISSUE TITLE
Label encoding w/ branching?

### ISSUE THREAD

**Issue by ju7ien** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#33]
Label encoding has 2 sub-cases, distinguishing between single and super channels. Any reason not to encode the former as a "single-carrier super channel"? Several advantages:
- removes the branching level,
- every case is encoded as a subcarrier-flexi-n dictionnary (with a single entry for single channel), simplifying implementations,
- increases the consistency with draft-ietf-ccamp-optical-impairment-topology-yang, which reuses the OTSi-Group containing one or more OTSi's, as defined by the ITU-T.

That would end up into something like:

    +--:(flexi-grid)
       +--rw rw subcarrier-flexi-n* [flexi-n]
          +--rw flexi-n    l0-types:flexi-n
          +--rw flexi-m?   l0-types:flexi-m

**Comment by sergiobelotti** [comment]
> This would be more efficient, but a few impacts with this change, including impact with with layer-0-types and optical-impairment-topology models.
> 
> No strong opinion on the change at this point.

I do not see impact at the moment in optical-impairment-topology: the model is not using "flexi-grid-label-hop" grouping where this branching is defined.

**Comment by sergiobelotti** [comment]
> > As pointed out by Aihua, neither in WSON nor in flexi-grid there is any min-element statement that precludes using the (super) case for a single channel with a list of one element.
> > An alternative option could be not to change the YANG model but to clarify that the (super) case can be used also for single channel e.g. in the layer0-types-ext.
> 
> I'd prefer the opposite: if the branching remains, then there should be a unique way to describe a single-channel label (i.e., prevent the use of _super_ in case of single n). Otherwise, interoperability issues can be expected...

let's do not change the model , as proposed by Italo and to agree a text to add in the draft.
What about : "Even if ,in the grouping flexi-grid-label-hop, in the branching  the (super) case could ,synthetically,  be used also for single channel , the suggestion is to use  a unique way to describe a single-channel label to avoid interoperability issues in case for single channel you would use the "supe" option in the branch."

**Comment by sergiobelotti** [comment]
weekly call 05-16-23

Decision:
We can suggest to deprecate the choice in the YANG code of "flexi-grid-label-hop" grouping and use instead a single list.
This update impacting the syntanx but not semantically the structure is avoiding problem for interoperability .
We need to share the update in the mailing list.

OLD

    +--:(flexi-grid)
       +--rw (single-or-super-channel)?
          +--:(single)
          |  +--rw flexi-n?              l0-types:flexi-n
          |  +--rw flexi-m?              l0-types:flexi-m
          +--:(super)
             +--rw subcarrier-flexi-n* [flexi-n]
                +--rw flexi-n    l0-types:flexi-n
                +--rw flexi-m?   l0-types:flexi-m

NEW

    +--:(flexi-grid)
       x--rw (single-or-super-channel)?
       |  x--:(single)
       |  |  x--rw flexi-n?              l0-types:flexi-n
       |  |  x--rw flexi-m?              l0-types:flexi-m
       |  x--:(super)
       |     x--rw subcarrier-flexi-n* [flexi-n]
       |        x--rw flexi-n    l0-types:flexi-n
       |        x--rw flexi-m?   l0-types:flexi-m
       +--rw tbd* [flexi-n]
          +--rw flexi-n    l0-types:flexi-n
          +--rw flexi-m?   l0-types:flexi-m

**Comment by sergiobelotti** [comment]
Call on 09-26-23:
Esther/Aihua: suggested to add "min-elements" statement to the list under the "super" branch, imposing a constraints that avoids to use the list for single element (then for single-channel).
Post-meeting notes: 
Sergio: to do that a new grouping , a copy of "flex-grid-label-hop" has to be defined since per backward compatibility we cannot modify the original grouping (defined in RFC9093).

```
grouping flexi-grid-label-hop {
    description
      "Generic label-hop information for flexi-grid";
    choice single-or-super-channel {
      description
        "single or super channel";
      case single {
        uses flexi-grid-frequency-slot;
      }
      case super {
        list subcarrier-flexi-n {
          key "flexi-n";
          uses flexi-grid-frequency-slot;
          min-elements 2;
          description
            "List of subcarrier channels for flexi-grid super
             channel.";
        }
      }
    }
    reference
      "RFC 7698: Framework and Requirements for GMPLS-Based Control
       of Flexi-Grid Dense Wavelength Division Multiplexing (DWDM)
       Networks";
  }
```
