### ISSUE TITLE
Clarification of layer0 label definitions

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#5]
The layero-types defines groupings for augmenting generic TE label for layer0 (WSON and flexi-grid) but there is no description about the concept of layer0 label.

It may be worthwhile adding a paragraph similar to https://tools.ietf.org/html/draft-ietf-ccamp-layer1-types-06#section-4.3 for layer0 labels.

See also: https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/pull/1/files?file-filters%5B%5D=.yang#r490981902

**Comment by sergiobelotti** [comment]
@italobusi : I completely agree with your comment. As for ODU case, we need for WSON and Flexgrid a description of what is the information needed to characterise the label in the two cases . In the media layer , frequency slot is the entity that is switched, and  label should describe essential parameter related to frequency slot, I would say NCFG (nominal central frequency granularity) or channel spacing,   and SWG (slot width granularity) .

**Comment by sergiobelotti** [comment]
> The layero-types defines groupings for augmenting generic TE label for layer0 (WSON and flexi-grid) but there is no description about the concept of layer0 label.
> 
> It may be worthwhile adding a paragraph similar to https://tools.ietf.org/html/draft-ietf-ccamp-layer1-types-06#section-4.3 for layer0 labels.
> 
> See also: https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/pull/1/files?file-filters%5B%5D=.yang#r490981902

weekly call 05-30-23:
We agree that we need to add this specific section.
