### ISSUE TITLE
Add needed standard reference

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#6]
More references are needed to where attributes and identities are defined. Need to review and add where is needed the correct reference.

Please see related comment https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/pull/4#pullrequestreview-439527955.

**Comment by italobusi** [comment]
Updated list of definitions or standard references to be provided:
- modulation format;
- Power mode
- SNR and GSNR
- PSD
- PMD
- Penalty Loss (PL)

**Comment by ggrammel** [comment]
-    modulation format: doesn't seem to have a definition. The best reference I could find was [G.Sup39](https://www.itu.int/rec/T-REC-G.Sup39/recommendation.asp?lang=en&parent=T-REC-G.Sup39-201602-I)
> This edition adds further information on modulation formats;
clarifies power budget parameters for systems with optical amplifiers; provides further information on
the optical signal-to-noise ratio (OSNR) measurement;

- Power mode: This is about operating Amplifiers which AFAIK are not subject to Standardization in ITU-T
- OSNR can again be found in[G.Sup39](https://www.itu.int/rec/T-REC-G.Sup39/recommendation.asp?lang=en&parent=T-REC-G.Sup39-201602-I) but it's rather a description. [G.977.1](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-G.977.1-202010-I!!PDF-E&type=items) also refers to the earlier but has a better definition. Suggest to use G.977.1 as a reference.
- GSNR is defined in [G.977.1](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-G.977.1-202010-I!!PDF-E&type=items)
 - PSD [G.9700](https://www.itu.int/rec/dologin_pub.asp?lang=f&id=T-REC-G.9700-201907-I!!PDF-E&type=items)
 - PMD [G.666](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-G.666-201102-I!!PDF-E&type=items)
  - Penalty Loss (PL): Don't think there is an ITU-T definition of it as the term alone looks quite "sloppy". Could not find a good reference
