### ISSUE TITLE
Question from Julien during Last Call (Jan, 2022)

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#61]
See for more details: https://mailarchive.ietf.org/arch/msg/ccamp/HU8iMblztB8hyn1uBbLscK6jUQY/

**Comment by sergiobelotti** [comment]
@ju7ien , @EstherLerouzic : there is a proposal to solve the issue you raised 
Proposal:
"In fact, section 3.1 of RFC8363 clarifies that:

From RFC8363   <...> Available
   central frequencies are advertised for m=1, which means that for an
   available central frequency n, the frequency slot from central
   frequency n-1 to central frequency n+1 is available

If we understand correctly, the proposal from Julien&Esther is to advertise the range of the available values of n for m=4 (50GHz)
We are wondering why not aligning the flexi-grid topology with the approach used in RFC8363 and to clarify that the available nominal central frequencies are correlated with m=1
We are also wondering whether this clarification should be provided in the flexi-grid I-D or in the layer0-types that defines the re-usable grouping used to describe the nominal central frequencies availability "

**Comment by ju7ien** [comment]
> We are wondering why not aligning the flexi-grid topology with the approach used in RFC8363 and to clarify that the available nominal central frequencies are correlated with m=1
That's clearly the (only) way to proceed. If already specified in an RFC, then we MUST be consistent. (m=4 was just a proposal to fill in the hole if any, certainly not meant to tweak an existing definition).

> We are also wondering whether this clarification should be provided in the flexi-grid I-D or in the layer0-types that defines the re-usable grouping used to describe the nominal central frequencies availability
The simple fact that we started this thread shows that it makes sens to remind this assumption in YANG topology I-Ds, all the more as many YANG module implementers know nothing about preexisting IETF protocols and associated definitions.

**Comment by sergiobelotti** [comment]
> > We are wondering why not aligning the flexi-grid topology with the approach used in RFC8363 and to clarify that the available nominal central frequencies are correlated with m=1
> > That's clearly the (only) way to proceed. If already specified in an RFC, then we MUST be consistent. (m=4 was just a proposal to fill in the hole if any, certainly not meant to tweak an existing definition).
> 
> > We are also wondering whether this clarification should be provided in the flexi-grid I-D or in the layer0-types that defines the re-usable grouping used to describe the nominal central frequencies availability
> > The simple fact that we started this thread shows that it makes sens to remind this assumption in YANG topology I-Ds, all the more as many YANG module implementers know nothing about preexisting IETF protocols and associated definitions.

@ju7ien : are you suggesting to add this clarification in flexi-grid I-D , or in this document (RFC9093-bis)? Just to be sure...e if this is the case , we need to move this issue in flexi-grid I-D context.

**Comment by ju7ien** [comment]
@sergio: I believe it should at least been said in the flexi-grid I-D, but I think it wouldn't harm to mention it in this document as well, if there are pieces that are relevant to this issue. So my answer is : A or A+B. ;-)

**Comment by italobusi** [comment]
@ju7ien @sergiobelotti : IMHO, it is better to describe this in RFC9093-bis because the grouping defining the flexi-grid label range is defined in this draft and re-used in both flexi-grid topology and tunnel drafts/models

My 2 cents

**Comment by sergiobelotti** [comment]
> @ju7ien @sergiobelotti : IMHO, it is better to describe this in RFC9093-bis because the grouping defining the flexi-grid label range is defined in this draft and re-used in both flexi-grid topology and tunnel drafts/models
> 
> My 2 cents

I think this depends where you think to put this clarification: you have flexi-grid-label-range-info where is described slot-width-granularity leaf, but not sure this can be exhaustive and maybe also in flex-grid I-D should be added the same text somewhere

**Comment by ju7ien** [comment]
Then I'd prefer to include that reminder in both...

**Comment by sergiobelotti** [comment]
We can start to add the proposed text taking as base what is present in RFC8363.
