### ISSUE TITLE
Rx optical parameters for alignement with 400G-ZR spec.

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#63]
As reported here https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/issues/51#issuecomment-1169783555
check have been done in both  OpenZR+ and ZR specs on the optical parameters, and for alignment , Tx parameters have been added to the explicit mode list .
But we have still RX parameters:

- PMD (avg) tolerance

- Peak PDL tolerance
Shall we need to add also these ones to the model? 
See related Specs. at:
 [OIF-400ZR-01.0_reduced2.pdf](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/8898693/OIF-400ZR-01.0_reduced2.pdf)
[openzrplus_1p0.pdf](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/8898694/openzrplus_1p0.pdf)

**Comment by sergiobelotti** [comment]
weekly call 25 October
Gabriele said that the attributes should be added in RFC 9093-bis and then make reference to that in the other document.
We decide to reference OIF document in the YANG definition. No other description.

**Comment by italobusi** [comment]
While working on a YANG update, Sergio and I have got a doubt about the measurement unit for these two new attributes.

We have checked the measurement units for PMD in L0-Types and optical impairment topology models and found many cases.

In the list `polarization-dispersion-penalty` the PMD measurement unit is `ps`:

https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis/blob/e2ae8b64e85a5876c2085243a17f183face920b3/ietf-layer0-types.yang#L1313-L1334

In the `fiber-params` grouping the PMD measurement unitis in `sqrt(ps)`:

https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/d4d761dcec69cbba8d5492f4dc85e7e7ed91c36d/ietf-optical-impairment-topology.yang#L263-L267

In the `roadm-express `grouping the PMD measurement unit is `ps/(km)^0.5`:

https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/d4d761dcec69cbba8d5492f4dc85e7e7ed91c36d/ietf-optical-impairment-topology.yang#L279-L293

In the `roadm-add-path` grouping the PMD measurement unit is `ps`:

https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/d4d761dcec69cbba8d5492f4dc85e7e7ed91c36d/ietf-optical-impairment-topology.yang#L325-L338

In the `roadm-drop-path` grouping the PMD measurement unit is `ps/(km)^0.5`:

https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/d4d761dcec69cbba8d5492f4dc85e7e7ed91c36d/ietf-optical-impairment-topology.yang#L425-L438

**Comment by sergiobelotti** [comment]
> While working on a YANG update, Sergio and I have got a doubt about the measurement unit for these two new attributes.
> 
> We have checked the measurement units for PMD in L0-Types and optical impairment topology models and found many cases.
> 
> In the list `polarization-dispersion-penalty` the PMD measurement unit is `ps`:
> 
> https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis/blob/e2ae8b64e85a5876c2085243a17f183face920b3/ietf-layer0-types.yang#L1313-L1334
> 
> In the `fiber-params` grouping the PMD measurement unitis in `sqrt(ps)`:
> 
> https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/d4d761dcec69cbba8d5492f4dc85e7e7ed91c36d/ietf-optical-impairment-topology.yang#L263-L267
> 
> In the `roadm-express `grouping the PMD measurement unit is `ps/(km)^0.5`:
> 
> https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/d4d761dcec69cbba8d5492f4dc85e7e7ed91c36d/ietf-optical-impairment-topology.yang#L279-L293
> 
> In the `roadm-add-path` grouping the PMD measurement unit is `ps`:
> 
> https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/d4d761dcec69cbba8d5492f4dc85e7e7ed91c36d/ietf-optical-impairment-topology.yang#L325-L338
> 
> In the `roadm-drop-path` grouping the PMD measurement unit is `ps/(km)^0.5`:
> 
> https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/d4d761dcec69cbba8d5492f4dc85e7e7ed91c36d/ietf-optical-impairment-topology.yang#L425-L438

for the fiber ps is correct or ps/sqrt(km) 0.5
all the other should be ps

**Comment by sergiobelotti** [comment]
weekly call 23-06-27

We agree do not add these two attributes since both for PMD and PDL are already covered in the model in the transceivers related attributes with "_polarization-dispersion-penalty_"  and "_max-pol-dependent-loss-penalty_" 
So, the issue can be considered closed.
