### ISSUE TITLE
Yangdoctors last call review of draft-ietf-ccamp-rfc9093-bis-04

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#68]
See https://mailarchive.ietf.org/arch/msg/ccamp/JQTGEyfyaEY7_DHDJQ-v8ww0bRo/

Reviewer: Joe Clarke
Review result: Ready with Issues

I have been asked to review this document on behalf of YANG Doctors.  While I
do not have domain experience in layer 0 optical, I found the document and YANG
module fairly easy to get through.  Since this document is a bis for RFC9093, I
did a pyang check to make sure that there are no backwards-incompatible changes
between the 9093 version and this one.  I did not find any.  The new module
adds new types, identities, and nodes.

In terms of issues, the leafref and must in the transceiver-mode are relative
back to the transceiver-capabilities grouping, which uses the transceiver-mode
grouping.  But what if transceiver-mode is used outside of this context?  Those
references may break.

> I see the point. We should change the leafref and must in absolute path, right?

In terms of nits, I found an inconsistent use of first-letter capitalization
and period termination in descriptions. 

> OK we will review and make the module more consistent

 I also noted that both the document
and the module lack an overall summary of changes between this version and the
9093 version (and I'm just setting the interrupt bit to make sure the authors
address that). 

- We have in fact a specific issue [#40](https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis/issues/40) in github for that saying “ Add description of the changes from RFC 9093 both in the YANG revision statement as well as in Appendix A”. Thanks to remind us.

 There is also an inconsistent use of quotes around various
 #units.

> Yes, I see, we will fix the inconsistencies.

I notice that there are some config true nodes that are a union with "empty" as
being one of the options.  Some of the nodes explain when to use empty, but
others do not.  I think it would be good to be consistent with the "empty"
explanation.

>The typical rational to use “empty” is this one:  
if the value of a mandatory attribute is unknown, it MUST be reported using the empty type.
If an optional attribute is applicable but its value is unknown, it MUST be reported using the empty type.
To avoid inconsistency we could add this piece of text in the description of the module.

**Comment by sergiobelotti** [comment]
#40

**Comment by italobusi** [comment]
> See https://mailarchive.ietf.org/arch/msg/ccamp/JQTGEyfyaEY7_DHDJQ-v8ww0bRo/
> 
> Reviewer: Joe Clarke Review result: Ready with Issues
> 
> I have been asked to review this document on behalf of YANG Doctors. While I do not have domain experience in layer 0 optical, I found the document and YANG module fairly easy to get through. Since this document is a bis for RFC9093, I did a pyang check to make sure that there are no backwards-incompatible changes between the 9093 version and this one. I did not find any. The new module adds new types, identities, and nodes.
> 
> In terms of issues, the leafref and must in the transceiver-mode are relative back to the transceiver-capabilities grouping, which uses the transceiver-mode grouping. But what if transceiver-mode is used outside of this context? Those references may break.
> 
> > I see the point. We should change the leafref and must in absolute path, right?
> 

**Italo, Sergio**: Changing to relative path is not possible because we need to point to the same network, node, ttp, transceiver through another relative path. We have moved the code with leafref and must statements to the transceiver-capabilities grouping. A similar code (with adjusted relative paths) should be added by anyone using the transceiver-mode grouping elsewhere.

> In terms of nits, I found an inconsistent use of first-letter capitalization and period termination in descriptions.
> 
> > OK we will review and make the module more consistent
> 

> I also noted that both the document and the module lack an overall summary of changes between this version and the 9093 version (and I'm just setting the interrupt bit to make sure the authors address that).
> 
> > We have in fact a specific issue [#40](https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis/issues/40) in github for that saying “ Add description of the changes from RFC 9093 both in the YANG revision statement as well as in Appendix A”. Thanks to remind us.
> 

> There is also an inconsistent use of quotes around various #units.
> 
> > Yes, I see, we will fix the inconsistencies.
> 

> I notice that there are some config true nodes that are a union with "empty" as being one of the options. Some of the nodes explain when to use empty, but others do not. I think it would be good to be consistent with the "empty" explanation.
> 
> > The typical rational to use “empty” is this one:
> > if the value of a mandatory attribute is unknown, it MUST be reported using the empty type.
> > If an optional attribute is applicable but its value is unknown, it MUST be reported using the empty type.
> > To avoid inconsistency we could add this piece of text in the description of the module.

**Italo, Sergio**: We have updated all the descriptions to be consistent. The only config true attribute is the tx-channel-power which in some cases it is also used as config false. We have added a MUST in the description to limit the use of empty value only when the attribute is config false.
