### ISSUE TITLE
Review dbm-t versus power-in-dbm data types

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#77]
power-in-dbm-or-null?

_Originally posted by @ju7ien in https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis/pull/70#discussion_r1256029682_

In general it is not clear which attributes should use the dbm-t and which attribute should use the power-in-dbm (or power-in-dbm-or-null) data type

**Comment by sergiobelotti** [comment]
Call on 09/19-23:
It is not clear which attributes should use the dbm-t and which attribute should use the power-in-dbm (or power-in-dbm-or-null) data type.
Looking at the definitions of dbm-t and power-in-dbm, there was substantial agreement that power-in-dbm is more clear and preferred definition.

**AP@all**: to review OI YANG module, RFC9093-bis and draft-ietf-ccamp-dwdm-if-param-yang to check the usage of dbm-t and possibly convert these definition using power-in-dbm.
