### ISSUE TITLE
Update wavelength assignment definitions

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#88]
c/wavelength-assignment/wavelength-assignment-rule/

Move the identities defined in WDM tunnel model: see https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-wdm-tunnel-yang/issues/64

**Comment by italobusi** [comment]
Discussed during the WDM tunnel call on 18 January 2024

**Comment by sergiobelotti** [comment]
It seems to me this issue is exactly the same of issue #92 . 
I would propose to delete one of the two.

**Comment by sergiobelotti** [comment]
We close the issue since it is a duplication of issue #92
